### ISSUE TITLE
Wrong SC size calculation

### ISSUE THREAD

**Issue by bonfus** [positivemuon/musConv#4]
This is wrong

https://github.com/positivemuon/musConv/blob/52d4ab2af172970ee3b25ac6e613aed414be416e/musConv/supcgen.py#L53

the volume (the determinant) should be used.

**Comment by bonfus** [comment]
See also

https://github.com/positivemuon/musConv/blob/52d4ab2af172970ee3b25ac6e613aed414be416e/musConv/supcgen.py#L53

**Comment by ionuorah** [comment]
Generally  for comparing two structures with their matrix transformation it may not be correct, but in this context it is correct, the length of the lattice vector is an input in this situation. 

Can we check with a situation where the whole function as it is fails?  It will be nice to see it.

**Comment by bonfus** [comment]
It is only correct if alpha, beta and gamma are always exactly 90 deg. I don't think this is generally the case.
It's easy to make an example.

**Comment by ionuorah** [comment]
I check in a number of cases where alpha, beta and gamma are not 90 deg and  it is completely fine, the length of the lattice vector was used as an input, moreover the size of the supercell as it is seems sufficient for what it is needed for. 

To do it using the volume (the determinant) and accesing the transformation matrix will require more lines of code and perhaps a function of its own, but  the need of the code is  fine with a line. 

I have been trying to see where it fails but not yet.  Perhaps finding one will help to understand why it does fail.

**Comment by bonfus** [comment]
I don't see how this can work when the transformation matrix is not diagonal. By definition basis vectors are "mixed". I think it's likely to happen when you have, for example, hexagonal lattices.

**Comment by ionuorah** [comment]
I think it works because the function with its inputs settings (not user defined) return a supercell with same alpha,beta and gamma as the input structure, and thus the magnitude of the lattice vectors of the new supercell are integer multiples of the input structure.   I think like this it flows with other alogrithm of the classes. If it doesn't work like this some of other parts have to be altered too.

It works with basically all the cifs I have checked , hexagonal, orthohombic, monoclinic, etc.

So it is important to find a case where it doesn't work, so we can figure out why it doesn't work.

**Comment by bonfus** [comment]
>  return a supercell with same alpha,beta and gamma as the input structure

Yes, if this is by definition is fine, but should be mentioned in the comments of the code line mentioned above.
Anyway, the algorithm isn't that smart if it does not convert an hexagonal cell into its orthorombic equivalent one.

> So it is important to find a case where it doesn't work, so we can figure out why it doesn't work.

It depends on the algorithm implemented by pymatgen. I can easily give you two cells with the latter "more cubic" than the former where the lattice parameters are not just scaled.

**Comment by bonfus** [comment]
Here's an example:

Si, FCC lattice vectors:

               a(1) = (  -5.137000   0.000000   5.137000 )
               a(2) = (   0.000000   5.137000   5.137000 )
               a(3) = (  -5.137000   5.137000   0.000000 )

Si, Simple Cubic (conventional) lattice vectors:

               a(1) = (   10.274000   0.000000   0.000000 )
               a(2) = (   0.000000   10.274000   0.000000 )
               a(3) = (   0.000000   0.000000   10.274000 )

**Comment by ionuorah** [comment]
I get, you can represent Si with FCC with 1 basis,  or SC with 4 basis.

But not sure I understand  the example in relation to the class. Does the code actually do this?

Like when an input of Si of FCC lattice vector is given as an input in the code,  it returns a supercell  with a simple cubic lattice vector?  If this is the case then  there is  a fundamental problem with the pymatgen nearcubic supercell generator and we should report the bug. 

I tried  and this is what I get.

primitive cell
 input
-2.690500 -2.690500 0.000000
-2.690500 0.000000 -2.690500
0.000000 -2.690500 -2.690500
 output
-5.381000 -5.381000 0.000000
-5.381000 0.000000 -5.381000
0.000000 -5.381000 -5.381000
#----------------------------------
Conventional unitcell 
input
5.381000 0.000000 0.000000
0.000000 5.381000 0.000000
0.000000 0.000000 5.381000

output
10.762000 0.000000 0.000000
0.000000 10.762000 0.000000
0.000000 0.000000 10.762000

**Comment by bonfus** [comment]
Ok, so pymatgen code is kind of crap.
What happens if you use this input?
https://www.crystallography.net/cod/1008152.html

**Comment by bonfus** [comment]
I tried with MnO, pymatgen works great, it finds the cubic cell and indeed

```
> atoms = read('MnO.out')
> res = cbst.apply_transformation(AseAtomsAdaptor.get_structure(atoms))
> cbst = CubicSupercellTransformation(min_length=8)
> np.divide(res.lattice.abc,AseAtomsAdaptor.get_structure(atoms).lattice.abc)
array([1.6508869, 1.6508869, 1.6508869])
```

[MnOTEST1.TXT](https://github.com/positivemuon/musConv/files/10943149/MnOTEST1.TXT)


```
# coding: utf-8
import numpy as np
from pymatgen.core import Structure

st = Structure.from_file('./MnOTEMP.cif')

from pymatgen.transformations.advanced_transformations  import 
cbst = CubicSupercellTransformation(min_length=8)

res = cbst.apply_transformation(st)

np.divide(res.lattice.abc,st.lattice.abc)
```

[MnOTEMP.TXT](https://github.com/positivemuon/musConv/files/10942907/MnOTEMP.TXT)

**Comment by ionuorah** [comment]
Not sure I still get it.

 Ofcourse , np.divide(supercell.lattice.abc,unitcell.lattice.abc)  to get the size of the supercell cannot be generally correct.
 
 But in the function where it was used it, it is correct, because of the inputs and what the function does.
 
 Not sure I understand what the problem is.  It gives a wrong result in the function where it was used?  
 
 This  "np.divide(res.lattice.abc,AseAtomsAdaptor.get_structure(atoms).lattice.abc)" for  sure is not  in the function.  It is a different operation from what the function does.
