### ISSUE TITLE
How to deal with big cells with rare species

### ISSUE THREAD

**Issue by bonfus** [positivemuon/musConv#5]
This condition

https://github.com/positivemuon/musConv/blob/52d4ab2af172970ee3b25ac6e613aed414be416e/musConv/chkconv.py#L132

may always be false for feasible supercells.

**Comment by ionuorah** [comment]
I don't think it is always false. It is rarely false.   len(specie_index) here returns how many atoms of a particular specie are in the structure.

In a case where it is false for all the atomic species. Then the exponential fit doesn't work there, we consider only the first criteria. 

Moreover, mnasf can be changed, but as we earlier agreed, atleast 5 points ( 5 atomic forces) are needed for an exponential fit.
