### ISSUE TITLE
Does not work with recent pymatgen

### ISSUE THREAD

**Issue by bonfus** [positivemuon/musConv#6]
My pymatgen version
```
pip list | grep pymatgen
pymatgen                 2023.2.28
```

Error
```
python musConv/supcgen.py ~/Data/Wip/MnO/DipTensor/MnO.cif
Traceback (most recent call last):
  File "/tmp/musConv/musConv/supcgen.py", line 3, in <module>
    from pymatgen.analysis.defects.generators import VoronoiInterstitialGenerator
ModuleNotFoundError: No module named 'pymatgen.analysis.defects'
```

**Comment by ionuorah** [comment]
As in the first lines of the code, for (pymatgen>=2022.10.22) the pymatgen extension (pymatgen-analysis-defects) is required to be installed separately. They restructured pymatgen!

**Comment by bonfus** [comment]
I see, should be added in the package dependencies, so one istalls everything with
```
pip install .
```

**Comment by ionuorah** [comment]
Yea, it is already in the To Do, in the readme

**Comment by bonfus** [comment]
Ok, close this issue when done.
