### ISSUE TITLE
Test on huge set

### ISSUE THREAD

**Issue by bonfus** [positivemuon/musConv#7]
This can is a draft to test musConv on a large set of CIF files

```
# coding: utf-8
import sys
import random
from ase.io import read
from ase.data import atomic_numbers
from ase.atom import Atom
from ase.calculators.lj import LennardJones
import numpy as np
from musConv.chkconv import check_SC_convergence

try:
    atoms = read(sys.argv[1])
except:
    sys.exit()

valid_atom = set(atomic_numbers.keys()) - set(atoms.get_chemical_symbols())

imp = random.sample(valid_atom, 1)[0]

atoms.append(Atom(imp, np.random.random(3)))
atoms.set_calculator(LennardJones())
atoms.get_forces()



csc   = check_SC_convergence(atoms,atoms.get_forces(),mu_num_spec=imp)
cond  = csc.apply_first_crit()
cond2 = csc.apply_2nd_crit()
print(f"Convergence of 1st criteria is {cond}, while 2nd criteria is {cond2}")
```

Many undocumented exceptions are raised.

**Comment by ionuorah** [comment]
It worked fine for me. I got only the  'prints' I left in the code to see what happens which will be later refined, depending on the workchain.

This is what the code above prints for me. 

"""
First SC convergence Criteria  NOT achieved
For specie Fe the 2nd SC convergence is NOT achieved, min dist required is 10.159411694927224 Ang 
The current SC size is NOT sufficient for convergence checks on specie--> C
Convergence of 1st criteria is False, while 2nd criteria is [False, False]
"""
I expect this from the code as it is now. I used a CFe2 (hexagonal) cif, for the intiial atom read.

**Comment by ionuorah** [comment]
Can you post the exceptions  that were raised for you?

**Comment by bonfus** [comment]
I just tried with all the cif files that I have on my laptop, but the code needs to be adapted to work with materials project for example.

**Comment by ionuorah** [comment]
Not sure I get it,  why we need to adapt it to material project.

**Comment by bonfus** [comment]
Nothing to adapt in your code, it's just the test above that can be easily interfaced with COD, materials cloud, or any other source of CIF.

**Comment by bonfus** [comment]
Final comment, this code can be used to test the whole iterative procedure without aiida. I think it's a good idea to get a feeling of the expected results.
