### ISSUE TITLE
Make min_lenght an input of the calcfunction

### ISSUE THREAD

**Issue by bonfus** [positivemuon/musConv#8]
Shouldn't the minimum image length:

https://github.com/positivemuon/musConv/blob/ef0abbde5863722324b7b458fbdf45b2df854df8/musConv/supcgen.py#L132

be an input of the code?

Edit: basically you can provide this length directly from the other routine that fits the forces, skipping directly to converged cell.

**Comment by ionuorah** [comment]
No, I think we don't want to do this. It will mess up the supercell generation algorithm. As we have to also put the max_atom  as input. They are related.   Instead,  to achieve something I think we  might alter  max_atoms=number of atoms*((2+factor)**3) or we put (2+factor)**3) as number of units we want from the input.

Or,  what we can do is to put some lines for the 'initialization' of the supercell calculation  to  be able to start from a user-given supercell size, if the user wants that else the automatic generation.  Then the 're_initialization' can continue from the automatic generation.

I think it is better we leave the structure of the code as it is in the time, let us get the Aiida-workchain  up first. 

From the little I have done on the workchain, I am seeing we have to totally restructure both chkconv.py and supcgen.py So it is better to wait for the workchain and do all once.

**Comment by bonfus** [comment]
Ok, let's keep this open and check at the next meeting.
